### PR TITLE
Fixes invalid XML in pom

### PR DESCRIPTION
**Pull request by viveleroi**

### CODE REVIEW

**Comment by awkay** [comment]
Give me a bit...I'm going to have to regenerate a PGP key to publish the thing, and find my password to Sonatype. If you don't hear from me in a day or so, just ping me...sorry, very busy.

**Comment by awkay** [comment]
I think I pushed it up to Maven central...not sure time delay. Let me know (0.18.3)

**Comment by viveleroi** [comment]
Thanks, I see the new version but there's no artifact jar, POM, etc. 

https://repo1.maven.org/maven2/org/gnu/gettext/libintl/0.18.3/

**Comment by awkay** [comment]
Argh...sonatype has such a horrific interface. I tried again. I check the content first and it showed the jar in there....not sure on delay.

**Comment by viveleroi** [comment]
Looks like it worked this time, thanks!

**Comment by awkay** [comment]
Welcome

**Pull request merged**
